#!/usr/bin/env python
# -*- coding:utf-8 -*-
# shaozx@gmail.com 2009-05-06
#
# 在控制台使用 cd 命令时用拼音补全中文路径
#
# 实验目录如下：
# biff@lenovo:/domain/WorkSpace$ ls
# SVN培训  全球眼  浙江建行  浙江农信
#
# 使用: (输完后按 TAB 键自动补全)
#    cd S     <tab>             进入[SVN培训]
#    cd q     <tab>             进入[全球眼]
#    cd z     <tab>             自动补全[浙江]
#    cd zj    <tab><tab>        提示[浙江建行 浙江农信]备选
#    cd 浙江j <tab>             进入[浙江建行]
#    cd zjj   <tab>             进入[浙江建行]
#    cd zj1   <tab>             进入[浙江建行]
#    cd zj2   <tab>             进入[浙江农信]
#
# 配置: ( 可以直接执行 sh install.sh 进行安装 )
#     找到 /etc/bash_completion 中 _file_dir() 函数，将
#        COMPREPLY=( "${COMPREPLY[@]}" "${toks[@]}" )
#     改成 ( 其中chsdir为本脚的名字,注意指定路径和赋执行权限 )
#        chs=($(chsdir "x$1" "$cur"))
#        COMPREPLY=( "${COMPREPLY[@]}" "${toks[@]}" "${chs[@]}" )
#     这是最简单的，但也是最不安全的。还有其它的方法，比如将这段函数粘到$HOME/.bashrc文件中,在引用/etc/bash_completion之后再覆盖性的定义一遍。或者另起一个文件保存这段脚本，然后在.bashrc中用 . $HOME/bin/myscript.sh 导入一遍。注意小点点。
#     上面的修改只对 cd 命令生效,如果其它地方也需要补全,比如vim,还要用相同的方法处理 _filedir_xspec() 函数
#
# 问题：
#  1、多音字无法解决,比如[浙江建行]要输入[zjjx];
#  2、大字符集输不进去，比如[草蜢]的"蜢"字,建议尽量少输入,用数字序号定位
#
# 祝Linux之行一路顺风!
# 有问题邮件联系!
#

import os,sys
import re,locale

def getPYSTR(s):
    s=unicode(s,"utf8")
    ret = ""
    for i in range(len(s)):
        ret += getPY(getSym(s[i]))
    return ret

def getSym(s):
    if s==unicode("～","UTF8"): return unicode("~","UTF8")
    if s==unicode("！","UTF8"): return unicode("!","UTF8")
    if s==unicode("＠","UTF8"): return unicode("@","UTF8")
    if s==unicode("＃","UTF8"): return unicode("#","UTF8")
    if s==unicode("＄","UTF8"): return unicode("$","UTF8")
    if s==unicode("％","UTF8"): return unicode("%","UTF8")
    if s==unicode("＆","UTF8"): return unicode("&","UTF8")
    if s==unicode("＊","UTF8"): return unicode("*","UTF8")
    if s==unicode("（","UTF8"): return unicode("(","UTF8")
    if s==unicode("）","UTF8"): return unicode(")","UTF8")
    if s==unicode("＿","UTF8"): return unicode("_","UTF8")
    if s==unicode("－","UTF8"): return unicode("-","UTF8")
    if s==unicode("＋","UTF8"): return unicode("+","UTF8")
    if s==unicode("［","UTF8"): return unicode("[","UTF8")
    if s==unicode("］","UTF8"): return unicode("]","UTF8")
    if s==unicode("＜","UTF8"): return unicode("<","UTF8")
    if s==unicode("＞","UTF8"): return unicode(">","UTF8")
    if s==unicode("？","UTF8"): return unicode("?","UTF8")
    if s==unicode("，","UTF8"): return unicode(",","UTF8")
    if s==unicode("。","UTF8"): return unicode(".","UTF8")
    if s==unicode("／","UTF8"): return unicode("/","UTF8")
    if s==unicode("、","UTF8"): return unicode(",","UTF8")
    return s

def getPY(s):
    try: s=s.encode("GB18030")
    except: pass
    if s<"\xb0\xa1": return s
    if s>"\xd7\xf9": return "?"
    if s<"\xb0\xc5": return "a"
    if s<"\xb2\xc1": return "b"
    if s<"\xb4\xee": return "c"
    if s<"\xb6\xea": return "d"
    if s<"\xb7\xa2": return "e"
    if s<"\xb8\xc1": return "f"
    if s<"\xb9\xfe": return "g"
    if s<"\xbb\xf7": return "h"
    if s<"\xbf\xa6": return "j"
    if s<"\xc0\xac": return "k"
    if s<"\xc2\xe8": return "l"
    if s<"\xc4\xc3": return "m"
    if s<"\xc5\xb6": return "n"
    if s<"\xc5\xbe": return "o"
    if s<"\xc6\xda": return "p"
    if s<"\xc8\xbb": return "q"
    if s<"\xc8\xf6": return "r"
    if s<"\xcb\xfa": return "s"
    if s<"\xcd\xda": return "t"
    if s<"\xce\xf4": return "w"
    if s<"\xd1\xb9": return "x"
    if s<"\xd4\xd1": return "y"
    if s<"\xd7\xfa": return "z"

if __name__== '__main__':
    if len(sys.argv) != 3 :
        sys.exit(1)

    dironly = sys.argv[1]
    cur = sys.argv[2]
    cur = cur.replace("\\","")

    idx=None; _cur=cur
    if len(cur)>1 and cur[-1:] >='0' and cur[-1:]<='9':
        idx = int(cur[-1])
        _cur = cur[:-1]

    _name=os.path.basename(_cur)

    name=os.path.basename(cur)
    dir=os.path.dirname(cur)
    if len(dir)==0 : dir="./"
    
    if not os.path.exists(dir):
        sys.exit(0)

    list = os.listdir(dir)

    if name in list or _name in list :
        sys.exit(0)

    ret = []
    for l in list:
        if l == getPYSTR(l) : continue
        l = l.replace("\\","")
        if l.find(name) == 0 or getPYSTR(l).find(getPYSTR(_name)) == 0:
            tmp = (dir+"/"+l).replace(".//","")
            if dironly == "x-d" and not os.path.isdir(tmp): continue
            ret.append( tmp )
    locale.setlocale(locale.LC_ALL,"")
    ret.sort(key=locale.strxfrm)
    if idx and len(ret) > idx-1:
        print ret[idx-1]
    else:
        print "\n".join(ret)

